local p = require("panda_colorscheme.palette")

return {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_dark },
    FloatBorder = { fg = p.parameter, bg = p.bg_dark },
    FloatTitle = { fg = p.self, bg = p.bg_dark, bold = true },
    FloatFooter = { link = "FloatTitle" },
    FloatShadow = { bg = p.bg_darker, blend = 80 },
    FloatShadowThrough = { bg = p.bg_darker, blend = 100 },
    MsgArea = { fg = p.fg, bg = p.bg },
    MsgSeparator = { fg = p.surface, bg = p.bg },

    Cursor = { fg = p.bg, bg = p.fg },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { fg = p.bg, bg = p.free },
    CursorLine = { bg = p.surface1 },
    CursorColumn = { bg = p.bg_dark },
    ColorColumn = { bg = p.surface },
    CursorLineNr = { fg = p.parameter, bg = p.surface1, bold = true },
    CursorLineSign = { link = "SignColumn" },
    CursorLineFold = { link = "FoldColumn" },

    LineNr = { fg = p.self, bg = p.surface },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    SignColumn = { fg = p.surface1, bg = p.surface },
    FoldColumn = { fg = p.overlay, bg = p.bg },
    Folded = { fg = p.parameter, bg = p.surface1 },

    StatusLine = { fg = p.fg, bg = p.bg_dark },
    StatusLineNC = { fg = p.surface1, bg = p.bg_dark },
    StatusLineTerm = { link = "StatusLine" },
    StatusLineTermNC = { link = "StatusLineNC" },
    WinSeparator = { fg = p.surface, bg = p.surface },
    VertSplit = { link = "WinSeparator" },
    WinBar = { fg = p.free, bg = p.bg },
    WinBarNC = { fg = p.self, bg = p.bg },

    Directory = { fg = p.parameter },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.overlay },
    SpecialKey = { link = "NonText" },
    Whitespace = { fg = p.surface1 },
    Conceal = { fg = p.subtle },

    ErrorMsg = { fg = p.white, bg = p.error_bg, bold = true },
    WarningMsg = { fg = p.global },
    MoreMsg = { fg = p.parameter },
    ModeMsg = { fg = p.fg, bold = true },
    Question = { fg = p.parameter },
    Title = { fg = p.parameter, bold = true },

    Visual = { fg = p.selected_fg, bg = p.selected_bg, bold = true },
    VisualNC = { bg = p.surface1 },
    VisualNOS = { bg = p.surface1, bold = true },
    Search = { fg = p.white, bg = p.search_bg },
    IncSearch = { fg = p.bg_dark, bg = p.attribute },
    CurSearch = { fg = p.selected_fg, bg = p.selected_bg },
    Substitute = { fg = p.free, bg = p.surface1 },
    MatchParen = { fg = p.global, bg = p.surface1, bold = true },
    QuickFixLine = { bg = p.surface1, bold = true },
    WildMenu = { fg = p.selected_fg, bg = p.selected_bg },

    Pmenu = { fg = p.self, bg = p.popup },
    PmenuSel = { fg = p.white, bg = p.surface1, bold = true },
    PmenuMatch = { fg = p.parameter, bold = true },
    PmenuMatchSel = { fg = p.parameter_unused, bg = p.surface1, bold = true },
    PmenuKind = { link = "Pmenu" },
    PmenuKindSel = { link = "PmenuSel" },
    PmenuExtra = { link = "Pmenu" },
    PmenuExtraSel = { link = "PmenuSel" },
    PmenuSbar = { bg = p.surface1 },
    PmenuThumb = { bg = p.overlay },
    ComplMatchIns = { fg = p.parameter, bold = true },

    TabLine = { fg = p.overlay, bg = p.bg_darker },
    TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
    TabLineFill = { bg = p.bg_dark },

    DiffAdd = { bg = p.diff_add },
    DiffDelete = { bg = p.diff_delete },
    DiffChange = { bg = p.diff_change },
    DiffText = { bg = p.diff_text, bold = true },
    diffAdded = { fg = p.attribute },
    diffRemoved = { fg = p.local_ },
    diffChanged = { fg = p.parameter },
    Added = { fg = p.attribute },
    Removed = { fg = p.local_ },
    Changed = { fg = p.parameter },

    SpellBad = { sp = p.local_, undercurl = true },
    SpellCap = { sp = p.global, undercurl = true },
    SpellRare = { sp = p.attribute, undercurl = true },
    SpellLocal = { sp = p.parameter, undercurl = true },
    Underlined = { underline = true },
    Ignore = { fg = p.bg },
    Error = { fg = p.local_ },
    Todo = { fg = p.bg, bg = p.free, bold = true },

    RedrawDebugNormal = { reverse = true },
    RedrawDebugClear = { fg = p.bg_darker, bg = p.unresolved },
    RedrawDebugComposed = { fg = p.bg_darker, bg = p.attribute },
    RedrawDebugRecompose = { fg = p.white, bg = p.error_bg },
}
