local p = require("panda_colorscheme.palette")

return {
    DiagnosticError = { fg = p.error },
    DiagnosticWarn = { fg = p.warn },
    DiagnosticInfo = { fg = p.parameter },
    DiagnosticHint = { fg = p.hint },
    DiagnosticOk = { fg = p.attribute },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { fg = p.error_bg, bg = p.surface },
    DiagnosticSignWarn = { fg = p.global, bg = p.surface },
    DiagnosticSignInfo = { fg = p.parameter, bg = p.surface },
    DiagnosticSignHint = { fg = p.hint, bg = p.surface },
    DiagnosticSignOk = { fg = p.attribute, bg = p.surface },
    DiagnosticVirtualTextError = { fg = p.error, bg = p.bg_dark },
    DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.bg_dark },
    DiagnosticVirtualTextInfo = { fg = p.parameter, bg = p.bg_dark },
    DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg_dark },
    DiagnosticVirtualTextOk = { fg = p.attribute, bg = p.bg_dark },
    DiagnosticVirtualLinesError = { link = "DiagnosticError" },
    DiagnosticVirtualLinesWarn = { link = "DiagnosticWarn" },
    DiagnosticVirtualLinesInfo = { link = "DiagnosticInfo" },
    DiagnosticVirtualLinesHint = { link = "DiagnosticHint" },
    DiagnosticVirtualLinesOk = { link = "DiagnosticOk" },
    DiagnosticUnderlineError = { sp = p.error, underline = true },
    DiagnosticUnderlineWarn = { sp = p.warn, underline = true },
    DiagnosticUnderlineInfo = { sp = p.parameter, underline = true },
    DiagnosticUnderlineHint = { sp = p.hint, underline = true },
    DiagnosticUnderlineOk = { sp = p.attribute, underline = true },
    DiagnosticUnnecessary = { fg = p.self, underline = true },
    DiagnosticDeprecated = { fg = p.self, strikethrough = true },

    LspDiagnosticsDefaultError = { link = "DiagnosticError" },
    LspDiagnosticsDefaultWarning = { link = "DiagnosticWarn" },
    LspDiagnosticsDefaultInformation = { link = "DiagnosticInfo" },
    LspDiagnosticsDefaultHint = { link = "DiagnosticHint" },
    LspDiagnosticsError = { link = "DiagnosticError" },
    LspDiagnosticsWarning = { link = "DiagnosticWarn" },
    LspDiagnosticsInformation = { link = "DiagnosticInfo" },
    LspDiagnosticsHint = { link = "DiagnosticHint" },
    LspDiagnosticsVirtualTextError = { link = "DiagnosticVirtualTextError" },
    LspDiagnosticsVirtualTextWarning = { link = "DiagnosticVirtualTextWarn" },
    LspDiagnosticsVirtualTextInformation = { link = "DiagnosticVirtualTextInfo" },
    LspDiagnosticsVirtualTextHint = { link = "DiagnosticVirtualTextHint" },
    LspDiagnosticsUnderlineError = { link = "DiagnosticUnderlineError" },
    LspDiagnosticsUnderlineWarning = { link = "DiagnosticUnderlineWarn" },
    LspDiagnosticsUnderlineInformation = { link = "DiagnosticUnderlineInfo" },
    LspDiagnosticsUnderlineHint = { link = "DiagnosticUnderlineHint" },

    LspCodeLens = { fg = p.overlay },
    LspCodeLensSeparator = { link = "LspCodeLens" },
    LspInlayHint = { fg = p.overlay, bg = p.popup },
    LspReferenceRead = { bg = p.reference_bg },
    LspReferenceText = { bg = p.reference_bg },
    LspReferenceWrite = { bg = p.reference_bg },
    LspReferenceTarget = { link = "LspReferenceText" },
    LspSignatureActiveParameter = { bg = p.surface, bold = true },
    SnippetTabstop = { link = "Visual" },

    ["@lsp"] = {},
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.event"] = { link = "@type" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { fg = p.free },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@constant.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@type.qualifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = {},
    ["@lsp.type.selfKeyword"] = { fg = p.self },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
    ["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },

    pythonBuiltin = { fg = p.builtin },
    ["@lsp.type.parameter.python"] = { fg = p.parameter },
    ["@lsp.type.function.python"] = { fg = p.attribute },
    ["@lsp.type.method.python"] = { fg = p.attribute },
    ["@lsp.type.class.python"] = { fg = p.imported, bold = true },
    ["@lsp.type.property.python"] = { fg = p.attribute },
    ["@lsp.type.namespace.python"] = { fg = p.imported, bold = true },
    ["@lsp.mod.global.python"] = { fg = p.global },
    ["@lsp.mod.builtin.python"] = { link = "pythonBuiltin" },
    ["@lsp.typemod.class.defaultLibrary.python"] = { link = "pythonBuiltin" },
    ["@lsp.typemod.function.defaultLibrary.python"] = { link = "pythonBuiltin" },
    ["@lsp.typemod.parameter.selfParameter.python"] = { fg = p.self },
    ["@lsp.typemod.parameter.unused.python"] = { fg = p.parameter_unused, underline = true },
}
