local p = require("panda_colorscheme.palette")

return {
    CmpItemAbbr = { fg = p.self },
    CmpItemAbbrDeprecated = { fg = p.overlay, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.parameter, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.parameter_unused, bold = true },
    CmpItemMenu = { fg = p.self },
    CmpItemKind = { fg = p.parameter },
    CmpItemKindText = { fg = p.self },
    CmpItemKindMethod = { fg = p.attribute },
    CmpItemKindFunction = { fg = p.attribute },
    CmpItemKindConstructor = { fg = p.imported, bold = true },
    CmpItemKindField = { fg = p.attribute },
    CmpItemKindVariable = { fg = p.local_ },
    CmpItemKindClass = { fg = p.imported, bold = true },
    CmpItemKindInterface = { fg = p.free },
    CmpItemKindModule = { fg = p.imported },
    CmpItemKindProperty = { fg = p.attribute },
    CmpItemKindUnit = { fg = p.attribute },
    CmpItemKindValue = { fg = p.local_ },
    CmpItemKindEnum = { fg = p.imported },
    CmpItemKindKeyword = { fg = p.keyword },
    CmpItemKindSnippet = { fg = p.free },
    CmpItemKindColor = { fg = p.local_ },
    CmpItemKindFile = { fg = p.parameter },
    CmpItemKindReference = { fg = p.local_ },
    CmpItemKindFolder = { fg = p.parameter },
    CmpItemKindEnumMember = { fg = p.local_ },
    CmpItemKindConstant = { fg = p.global },
    CmpItemKindStruct = { fg = p.imported },
    CmpItemKindEvent = { fg = p.builtin },
    CmpItemKindOperator = { fg = p.fg },
    CmpItemKindTypeParameter = { fg = p.parameter },
    CmpItemKindCopilot = { fg = p.attribute },

    GitSignsAdd = { fg = p.attribute },
    GitSignsChange = { fg = p.global },
    GitSignsDelete = { fg = p.local_ },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsAddLn = { bg = p.diff_add },
    GitSignsChangeLn = { bg = p.diff_change },
    GitSignsDeleteLn = { bg = p.diff_delete },
    GitSignsCurrentLineBlame = { fg = p.surface1 },
    GitSignsAddPreview = { link = "DiffAdd" },
    GitSignsDeletePreview = { link = "DiffDelete" },
    GitSignsChangedelete = { link = "GitSignsChange" },
    GitSignsTopdelete = { link = "GitSignsDelete" },
    GitSignsUntracked = { link = "GitSignsAdd" },

    TreesitterContext = { bg = p.surface },
    TreeSitterContext = { link = "TreesitterContext" },
    TreesitterContextBottom = { sp = p.surface, underline = true },
    TreesitterContextLineNumber = { fg = p.fg, bg = p.surface },
    TreesitterContextLineNumberBottom = { link = "TreesitterContextBottom" },
    TreesitterContextSeparator = { fg = p.parameter, bg = p.surface },

    SnacksIndent = { fg = p.surface, bold = true },
    SnacksIndentScope = { fg = p.parameter, bold = true },
    SnacksPicker = { link = "NormalFloat" },
    SnacksPickerBorder = { link = "FloatBorder" },
    SnacksPickerTitle = { link = "FloatTitle" },
    SnacksPickerInput = { link = "NormalFloat" },
    SnacksPickerMatch = { fg = p.parameter_unused, bold = true },
    SnacksPickerCursorLine = { link = "CursorLine" },
    SnacksPickerDir = { fg = p.self },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerPathHidden = { fg = p.overlay },
    SnacksPickerGitStatusUntracked = { fg = p.attribute },
    SnacksPickerGitStatusModified = { fg = p.global },
    SnacksPickerGitStatusDeleted = { fg = p.local_ },

    RenderMarkdownCustomH1Bg = { fg = p.attribute, bg = "#252535", bold = true },
    RenderMarkdownCustomH1Fg = { fg = p.attribute, bold = true },
    RenderMarkdownCustomH2Bg = { fg = p.global, bg = "#2a2a3a", bold = true },
    RenderMarkdownCustomH2Fg = { fg = p.global, bold = true },
    RenderMarkdownCustomH3Bg = { fg = p.parameter, bg = "#262636", bold = true },
    RenderMarkdownCustomH3Fg = { fg = p.parameter, bold = true },
    RenderMarkdownCustomH4Bg = { fg = p.local_, bg = "#2a2a3a", bold = true },
    RenderMarkdownCustomH4Fg = { fg = p.local_, bold = true },
    RenderMarkdownCustomH5Bg = { fg = p.free, bg = "#23232f", bold = true },
    RenderMarkdownCustomH5Fg = { fg = p.free, bold = true },
    RenderMarkdownCustomH6Bg = { fg = p.self, bg = p.bg, bold = true },
    RenderMarkdownCustomH6Fg = { fg = p.self, bold = true },
    markdownH1 = { link = "RenderMarkdownCustomH1Fg" },
    markdownH2 = { link = "RenderMarkdownCustomH2Fg" },
    markdownH3 = { link = "RenderMarkdownCustomH3Fg" },
    markdownH4 = { link = "RenderMarkdownCustomH4Fg" },
    markdownH5 = { link = "RenderMarkdownCustomH5Fg" },
    markdownH6 = { link = "RenderMarkdownCustomH6Fg" },
    markdownHeadingDelimiter = { fg = p.global, bold = true },
    RenderMarkdownH1 = { link = "RenderMarkdownCustomH1Fg" },
    RenderMarkdownH1Bg = { link = "RenderMarkdownCustomH1Bg" },
    RenderMarkdownH2 = { link = "RenderMarkdownCustomH2Fg" },
    RenderMarkdownH2Bg = { link = "RenderMarkdownCustomH2Bg" },
    RenderMarkdownH3 = { link = "RenderMarkdownCustomH3Fg" },
    RenderMarkdownH3Bg = { link = "RenderMarkdownCustomH3Bg" },
    RenderMarkdownH4 = { link = "RenderMarkdownCustomH4Fg" },
    RenderMarkdownH4Bg = { link = "RenderMarkdownCustomH4Bg" },
    RenderMarkdownH5 = { link = "RenderMarkdownCustomH5Fg" },
    RenderMarkdownH5Bg = { link = "RenderMarkdownCustomH5Bg" },
    RenderMarkdownH6 = { link = "RenderMarkdownCustomH6Fg" },
    RenderMarkdownH6Bg = { link = "RenderMarkdownCustomH6Bg" },
    RenderMarkdownBullet = { fg = p.parameter },
    RenderMarkdownCode = { bg = p.bg_dark },
    RenderMarkdownCodeInline = { bg = p.surface },
    RenderMarkdownTableHead = { fg = p.parameter },
    RenderMarkdownTableRow = { fg = p.imported },
    RenderMarkdownError = { link = "DiagnosticError" },
    RenderMarkdownWarn = { link = "DiagnosticWarn" },
    RenderMarkdownInfo = { link = "DiagnosticInfo" },
    RenderMarkdownHint = { link = "DiagnosticHint" },
    RenderMarkdownSuccess = { link = "DiagnosticOk" },

    DapBreakpoint = { fg = p.local_ },
    DapStopped = { fg = p.free },
    DapStoppedText = { fg = p.attribute, bg = p.dap_stopped },
    DapStoppedLine = { bg = p.dap_stopped },
    DapUIWinSelect = { fg = p.global, bold = true },
    DapUIRestart = { fg = p.attribute },
    DapUIStop = { fg = p.local_ },
    DapUIStepInto = { fg = p.parameter },
    DapUIStepOver = { fg = p.parameter },
    DapUIBreakpointsDisabledLine = { fg = p.surface2 },
    DapUIBreakpointsCurrentLine = { fg = p.attribute, bold = true },
    DapUIBreakpointsInfo = { fg = p.attribute },
    DapUIBreakpointsPath = { fg = p.parameter },
    DapUIWatchesError = { fg = p.local_ },
    DapUIWatchesValue = { fg = p.attribute },
    DapUIWatchesEmpty = { fg = p.local_ },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUILineNumber = { fg = p.parameter },
    DapUISource = { fg = p.parameter_unused },
    DapUIStoppedThread = { fg = p.parameter },
    DapUIThread = { fg = p.attribute },
    DapUIDecoration = { fg = p.parameter },
    DapUIModifiedValue = { fg = p.global },
    DapUIVariable = { fg = p.fg },
    DapUIValue = { fg = p.parameter },
    DapUIType = { fg = p.builtin },
    DapUIScope = { fg = p.parameter },

    TelescopeNormal = { link = "NormalFloat" },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopeTitle = { link = "FloatTitle" },
    TelescopePromptNormal = { link = "NormalFloat" },
    TelescopePromptBorder = { link = "FloatBorder" },
    TelescopePromptTitle = { fg = p.bg, bg = p.parameter, bold = true },
    TelescopePreviewTitle = { fg = p.bg, bg = p.attribute, bold = true },
    TelescopeResultsTitle = { fg = p.bg, bg = p.global, bold = true },
    TelescopeSelection = { link = "CursorLine" },
    TelescopeMatching = { fg = p.parameter_unused, bold = true },

    NoiceCmdline = { link = "NormalFloat" },
    NoiceCmdlinePopup = { link = "NormalFloat" },
    NoiceCmdlinePopupBorder = { link = "FloatBorder" },
    NoiceCmdlinePopupTitle = { link = "FloatTitle" },
    NoiceConfirm = { link = "NormalFloat" },
    NoiceConfirmBorder = { link = "FloatBorder" },
    NoiceCursor = { link = "Cursor" },
    NoiceFormatProgressDone = { fg = p.attribute, bg = p.surface },
    NoiceFormatProgressTodo = { fg = p.overlay, bg = p.surface },
    NoiceLspProgressSpinner = { fg = p.parameter },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceLspProgressClient = { fg = p.self },
    NotifyBackground = { bg = p.bg_dark },
    NotifyERRORBorder = { fg = p.local_ },
    NotifyWARNBorder = { fg = p.global },
    NotifyINFOBorder = { fg = p.parameter },
    NotifyDEBUGBorder = { fg = p.self },
    NotifyTRACEBorder = { fg = p.builtin },
    NotifyERRORTitle = { link = "DiagnosticError" },
    NotifyWARNTitle = { link = "DiagnosticWarn" },
    NotifyINFOTitle = { link = "DiagnosticInfo" },
    NotifyDEBUGTitle = { fg = p.self },
    NotifyTRACETitle = { fg = p.builtin },
    NotifyERRORIcon = { link = "DiagnosticError" },
    NotifyWARNIcon = { link = "DiagnosticWarn" },
    NotifyINFOIcon = { link = "DiagnosticInfo" },
    NotifyDEBUGIcon = { fg = p.self },
    NotifyTRACEIcon = { fg = p.builtin },

    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { fg = p.self, bold = true },
    MiniFilesCursorLine = { link = "CursorLine" },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { fg = p.fg },
    MiniFilesBorderModified = { link = "DiagnosticWarn" },
    MiniSurround = { fg = p.bg, bg = p.free },
    MiniIndentscopeSymbol = { fg = p.fg },
    MiniIndentscopePrefix = { nocombine = true },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticWarn" },
    MiniPickBorderText = { fg = p.builtin },
    MiniPickPrompt = { link = "DiagnosticInfo" },
    MiniPickMatchRanges = { link = "DiagnosticHint" },
    MiniPickMatchCurrent = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "NormalFloat" },

    AerialNormal = { link = "NormalFloat" },
    AerialLine = { link = "CursorLine" },
    AerialLineNC = { link = "CursorLine" },
    AerialGuide = { fg = p.surface1 },
    AerialClass = { link = "@type" },
    AerialFunction = { link = "@function" },
    AerialMethod = { link = "@function.method" },
    AerialVariable = { link = "@variable" },
    AerialProperty = { link = "@property" },

    NeotestAdapterName = { fg = p.builtin, bold = true },
    NeotestDir = { link = "Directory" },
    NeotestFile = { fg = p.fg },
    NeotestFocused = { bold = true, underline = true },
    NeotestIndent = { fg = p.surface1 },
    NeotestMarked = { fg = p.global, bold = true },
    NeotestNamespace = { fg = p.imported },
    NeotestPassed = { fg = p.attribute },
    NeotestRunning = { fg = p.global },
    NeotestSkipped = { fg = p.self },
    NeotestTarget = { fg = p.parameter },
    NeotestTest = { fg = p.fg },
    NeotestUnknown = { fg = p.self },
    NeotestWatching = { fg = p.parameter },
    NeotestFailed = { fg = p.local_ },

    TodoBgTODO = { fg = p.bg, bg = p.free, bold = true },
    TodoFgTODO = { fg = p.free },
    TodoSignTODO = { fg = p.free, bg = p.surface },
    TodoBgFIX = { fg = p.white, bg = p.error_bg, bold = true },
    TodoFgFIX = { fg = p.local_ },
    TodoSignFIX = { fg = p.local_, bg = p.surface },
    TodoBgWARN = { fg = p.bg, bg = p.global, bold = true },
    TodoFgWARN = { fg = p.global },
    TodoSignWARN = { fg = p.global, bg = p.surface },
    TodoBgNOTE = { fg = p.bg, bg = p.parameter, bold = true },
    TodoFgNOTE = { fg = p.parameter },
    TodoSignNOTE = { fg = p.parameter, bg = p.surface },
    TodoBgTEST = { fg = p.bg, bg = p.attribute, bold = true },
    TodoFgTEST = { fg = p.attribute },
    TodoSignTEST = { fg = p.attribute, bg = p.surface },

    MasonNormal = { link = "NormalFloat" },
    MasonHeader = { fg = p.bg, bg = p.parameter, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.global, bold = true },
    MasonHighlight = { fg = p.parameter },
    MasonHighlightBlock = { fg = p.bg, bg = p.parameter },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.parameter, bold = true },
    MasonMuted = { fg = p.self },
    MasonMutedBlock = { fg = p.bg, bg = p.self },
    MasonHighlightSecondary = { fg = p.global },

    LazyNormal = { link = "NormalFloat" },
    LazyButton = { fg = p.fg, bg = p.surface },
    LazyButtonActive = { fg = p.white, bg = p.surface1, bold = true },
    LazyCommit = { fg = p.global },
    LazyDimmed = { fg = p.overlay },
    LazyH1 = { fg = p.bg, bg = p.parameter, bold = true },
    LazyH2 = { fg = p.parameter, bold = true },
    LazyProp = { fg = p.self },
    LazyReasonCmd = { fg = p.builtin },
    LazyReasonEvent = { fg = p.attribute },
    LazyReasonFt = { fg = p.free },
    LazyReasonImport = { fg = p.imported },
    LazyReasonKeys = { fg = p.global },
    LazyReasonPlugin = { fg = p.local_ },
    LazyReasonRuntime = { fg = p.parameter },
    LazySpecial = { fg = p.builtin },
    LazyUrl = { fg = p.free, underline = true },
    LazyValue = { fg = p.local_ },

    RainbowDelimiterRed = { fg = p.local_ },
    RainbowDelimiterYellow = { fg = p.global },
    RainbowDelimiterBlue = { fg = p.parameter },
    RainbowDelimiterOrange = { fg = p.local_ },
    RainbowDelimiterGreen = { fg = p.attribute },
    RainbowDelimiterViolet = { fg = p.builtin },
    RainbowDelimiterCyan = { fg = p.parameter_unused },
    IblIndent = { fg = p.surface },
    IblScope = { fg = p.fg },

    NeoTreeNormal = { link = "NormalFloat" },
    NeoTreeNormalNC = { link = "NormalFloat" },
    NeoTreeDirectoryName = { link = "Directory" },
    NeoTreeDirectoryIcon = { link = "Directory" },
    NeoTreeRootName = { fg = p.parameter, bold = true },
    NeoTreeFileNameOpened = { fg = p.free },
    NeoTreeModified = { fg = p.global },
    NeoTreeGitAdded = { fg = p.attribute },
    NeoTreeGitDeleted = { fg = p.local_ },
    NeoTreeGitModified = { fg = p.global },
    NeoTreeGitConflict = { fg = p.local_ },
    NeoTreeGitIgnored = { fg = p.overlay },
    NeoTreeGitUntracked = { fg = p.builtin },
    NeoTreeIndentMarker = { fg = p.overlay },
    NeoTreeWinSeparator = { link = "WinSeparator" },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { link = "FloatTitle" },

    NvimTreeNormal = { link = "NormalFloat" },
    NvimTreeFolderName = { link = "Directory" },
    NvimTreeOpenedFolderName = { link = "Directory" },
    NvimTreeEmptyFolderName = { link = "Directory" },
    NvimTreeFolderIcon = { link = "Directory" },
    NvimTreeRootFolder = { fg = p.parameter_unused, bold = true },
    NvimTreeGitDeleted = { fg = p.local_ },
    NvimTreeGitNew = { fg = p.attribute },
    NvimTreeGitDirty = { fg = p.global },
    NvimTreeIndentMarker = { fg = p.overlay },
    NvimTreeSymlink = { fg = p.free },
    NvimTreeWinSeparator = { link = "WinSeparator" },
}
