local p = require("panda_colorscheme.palette")

return {
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.builtin },
    ["@variable.parameter"] = { fg = p.parameter },
    ["@variable.parameter.builtin"] = { fg = p.self },
    ["@parameter"] = { link = "@variable.parameter" },

    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = p.literal },
    ["@constant.macro"] = { link = "Macro" },
    ["@module"] = { fg = p.imported, bold = true },
    ["@module.builtin"] = { link = "@variable.builtin" },
    ["@namespace"] = { link = "@module" },
    ["@label"] = { link = "Label" },

    ["@string"] = { link = "String" },
    ["@string.regexp"] = { fg = p.local_ },
    ["@string.escape"] = { fg = p.builtin },
    ["@string.special"] = { link = "Special" },
    ["@string.special.path"] = { link = "Special" },
    ["@string.special.symbol"] = { link = "Special" },
    ["@string.special.url"] = { fg = p.free, underline = true },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },

    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },

    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = p.imported },
    ["@type.definition"] = { link = "Type" },
    ["@type.qualifier"] = { link = "Keyword" },
    ["@attribute"] = { fg = p.attribute },
    ["@attribute.builtin"] = { link = "Special" },
    ["@property"] = { fg = p.attribute },
    ["@field"] = { link = "@property" },

    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { fg = p.builtin },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@method"] = { link = "@function.method" },
    ["@method.call"] = { link = "@function.method.call" },
    ["@constructor"] = { fg = p.imported, bold = true },
    ["@operator"] = { link = "Operator" },

    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.modifier"] = { link = "StorageClass" },
    ["@keyword.operator"] = { link = "Operator" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },

    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Special" },

    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = p.white, bg = p.error_bg, bold = true },
    ["@comment.warning"] = { fg = p.bg, bg = p.global, bold = true },
    ["@comment.note"] = { fg = p.bg, bg = p.parameter, bold = true },
    ["@comment.todo"] = { fg = p.bg, bg = p.free, bold = true },

    ["@markup"] = { fg = p.fg },
    ["@markup.strong"] = { fg = p.free, bold = true },
    ["@markup.italic"] = { fg = p.free, italic = true },
    ["@markup.strikethrough"] = { fg = p.fg, strikethrough = true },
    ["@markup.underline"] = { link = "Underlined" },
    ["@markup.heading"] = { fg = p.parameter, bold = true },
    ["@markup.heading.1"] = { fg = p.attribute, bold = true },
    ["@markup.heading.2"] = { fg = p.global, bold = true },
    ["@markup.heading.3"] = { fg = p.parameter, bold = true },
    ["@markup.heading.4"] = { fg = p.local_, bold = true },
    ["@markup.heading.5"] = { fg = p.free, bold = true },
    ["@markup.heading.6"] = { fg = p.self, bold = true },
    ["@markup.link"] = { fg = p.parameter_unused, underline = true },
    ["@markup.link.label"] = { fg = p.attribute },
    ["@markup.link.url"] = { fg = p.free, underline = true },
    ["@markup.list"] = { fg = p.global },
    ["@markup.list.checked"] = { fg = p.attribute },
    ["@markup.list.unchecked"] = { fg = p.self },
    ["@markup.quote"] = { fg = p.self, italic = true },
    ["@markup.raw"] = { fg = p.attribute },

    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@tag"] = { fg = p.builtin },
    ["@tag.attribute"] = { fg = p.attribute },
    ["@tag.delimiter"] = { fg = p.self },
}
