# Git branch
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ <\1>/'
}

# terminal formatting
export PS1="\n\[\e[m\]\[\e[1;34m\][\@]:\[\e[m\]\[\e[1;33m\]\$(parse_git_branch) \\[\e[m\]\[\e[1;32m\]\w\n\[\e[m\]\[\e[1;37m\]\u$ "

# tmux
TERM=screen-256color

source ~/.aliases.sh
